version: "3"

services:
  db-postgres:
    image: postgres:alpine
    ports:
      - "5435:5432"
    container_name: "db-postgres"
    restart: always
    volumes:
      - ./data-base:/var/lib/postgresql/data
    
    environment:
      POSTGRES_USER: rubensdb
      POSTGRES_PASSWORD: fish4040

volumes:
    data-base: